spring.application.name=userservice

spring.datasource.url=jdbc:postgresql://localhost:5432/fitness-micro-user
spring.datasource.username=postgres
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true
eureka.instance.hostname=localhost

server.port=8081


#spring.main.banner-mode=off
#spring.main.log-startup-info=false
#logging.level.root=WARN
#logging.level.root=INFO
#logging.level.com.myapp=INFO
